# Header
menu:
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml
github: https://github.com/xiaogliu
logo_title: Going # 直接在文件里写死
blog_title: 刘小光的博客

# Content
excerpt_link: Read More
fancybox: true
mathjax: false

# Sidebar
sidebar: right
widgets:
- recent_posts
- tag
- archive

# Miscellaneous
wx_block: true
google_analytics:
favicon:
twitter:
google_plus:
fb_admins:
fb_app_id:

# Duoshuo
duoshuo_shortname:

# Swiftype Search
swiftype_key:
